<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var \Throwable $exception
 * @var array[] $actions
 * @var string[] $info
 * @var string $source
 * @var ?array $lastError
 * @var string[] $httpHeaders
 * @var callable $dump
 * @var array $snapshot
 * @var bool $showEnvironment
 * @var BlueScreen $this
 * @var bool $headersSent
 * @var ?string $headersFile
 * @var ?int $headersLine
 * @var ?array $obStatus
 */
?>
<div id="tracy-bs" itemscope>
	<a id="tracy-bs-toggle" href="#" class="tracy-toggle"></a>
	<div class="tracy-bs-main">
<?php $ex = $exception; $exceptions = []; ?>
<?php require __DIR__ . '/section-exception.phtml' ?>

<?php require __DIR__ . '/section-lastMutedError.phtml' ?>

<?php $bottomPanels = [] ?>
<?php foreach ($this->renderPanels(null) as $panel): ?>
<?php if (!empty($section->bottom)) { $bottomPanels[] = $panel; continue; } ?>
<?php $collapsedClass = !isset($section->collapsed) || $section->collapsed ? ' tracy-collapsed' : ''; ?>
		<div class="panel">
			<h2><a data-tracy-ref="^+" class="tracy-toggle<?= $collapsedClass ?>"><?= Helpers::escapeHtml($section->tab) ?></a></h2>

			<div class="inner<?= $collapsedClass ?>">
			<?= $section->panel ?>
			</div>
		</div>
<?php endforeach ?>

<?php require __DIR__ . '/section-environment.phtml' ?>

<?php require __DIR__ . '/section-cli.phtml' ?>

<?php require __DIR__ . '/section-http.phtml' ?>

<?php foreach ($bottomPanels as $panel): ?>
		<div class="panel">
			<h2><a data-tracy-ref="^+" class="tracy-toggle"><?= Helpers::escapeHtml($section->tab) ?></a></h2>

			<div class="inner">
			<?= $section->panel ?>
			</div>
		</div>
<?php endforeach ?>

		<footer>
			<ul>
				<li><b><a href="https://github.com/sponsors/dg" target="_blank" rel="noreferrer noopener">Please support Tracy via a donation 💙️</a></b></li>
				<li>Report generated at <?= date('Y/m/d H:i:s') ?></li>
				<?php foreach ($info as $item): ?><li><?= Helpers::escapeHtml($item) ?></li><?php endforeach ?>
			</ul>
			<div class="footer-logo"><a href="https://tracy.nette.org" rel="noreferrer"></a></div>
		</footer>
	</div>
	<meta itemprop=tracy-snapshot content=<?= Dumper::formatSnapshotAttribute($snapshot) ?>>
</div>
