<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var \Throwable $ex
 * @var int $expanded
 */

?>
<section class="section">
	<h2 class="section-label"><a data-tracy-ref="^+" class="tracy-toggle<?= ($collapsed = $expanded !== null) ? ' tracy-collapsed' : '' ?>">Source file</a></h2>

	<div class="section-panel<?= $collapsed ? ' tracy-collapsed' : '' ?>">
		<p><b>File:</b> <?= Helpers::editorLink($ex->getFile(), $ex->getLine()) ?></p>
		<?php if (is_file($ex->getFile())): ?><?= BlueScreen::highlightFile($ex->getFile(), $ex->getLine()) ?><?php endif ?>

	</div>
</section>
