<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var \Throwable $ex
 * @var \Throwable[] $exceptions
 * @var BlueScreen $this
 * @var array[] $actions
 * @var callable $dump
 */

$ex = $ex->getPrevious();
if (!$ex || in_array($ex, $exceptions, true)) {
	return;
}
$exceptions[] = $ex;
?>

<div class="panel"<?php if (count($exceptions) === 1) echo ' id="tracyCaused"' ?>>
	<h2><a data-tracy-ref="^+" class="tracy-toggle<?= ($collapsed = count($exceptions) > 1) ? ' tracy-collapsed' : '' ?>">Caused by</a></h2>

	<div class="<?= $collapsed ? 'tracy-collapsed ' : '' ?>inner">
<?php require __DIR__ . '/section-exception.phtml' ?>

	</div>
</div>
