<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var callable $dump
 * @var bool $showEnvironment
 * @var array $obStatus
 * @var BlueScreen $this
 */

if (!$showEnvironment) {
	return;
}
?>
<div class="panel">
	<h2><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">Environment</a></h2>

	<div class="tracy-collapsed inner">
		<h3><a data-tracy-ref="^+" class="tracy-toggle">$_SERVER</a></h3>
		<div class="outer">
			<table class="tracy-sortable">
<?php foreach ($_SERVER as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php endforeach ?>
			</table>
		</div>


		<h3><a data-tracy-ref="^+" class="tracy-toggle">$_SESSION</a></h3>
		<div class="outer">
<?php if (empty($_SESSION)):?>
			<p><i>empty</i></p>
<?php else: ?>
			<table class="tracy-sortable">
<?php	foreach ($_SESSION as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $k === '__NF' ? '<i>Nette Session</i>' : $dump($v, $k) ?></td></tr>
<?php	endforeach ?>
			</table>
<?php endif ?>
		</div>


<?php if (!empty($_SESSION['__NF']['DATA'])):?>
		<h3><a data-tracy-ref="^+" class="tracy-toggle">Nette Session</a></h3>
		<div class="outer">
			<table class="tracy-sortable">
<?php	foreach ($_SESSION['__NF']['DATA'] as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php	endforeach ?>
			</table>
		</div>
<?php endif ?>


<?php
$list = get_defined_constants(true);
if (!empty($list['user'])):?>
		<h3><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">Constants</a></h3>
		<div class="outer tracy-collapsed">
			<table class="tracy-sortable">
<?php	foreach ($list['user'] as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php	endforeach ?>
			</table>
		</div>
<?php endif ?>


		<h3><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">Configuration options</a></h3>
		<div class="outer tracy-collapsed">
			<?php $this->renderPhpInfo() ?>
		</div>


<?php if ($obStatus): ?>
		<h3><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">Output buffers status</a></h3>
		<div class="outer tracy-collapsed">
			<?php echo $dump($obStatus) ?>
		</div>
<?php endif ?>
	</div>
</div>
