<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var \Throwable $ex
 * @var callable $dump
 * @var int $expanded
 * @var array $stack
 */

if (!$stack) {
	return;
}
?>
<section class="section">
	<h2 class="section-label"><a data-tracy-ref="^+" class="tracy-toggle">Call stack</a></h2>

	<div class="section-panel">
	<div class="callstack">
<?php foreach ($stack as $key => $row): ?>
<?php	$clickable = !empty($row['args']) || (isset($row['file']) && is_file($row['file'])) ?>

		<div class="callstack-file">
<?php	if (isset($row['file']) && is_file($row['file'])): ?>
			<?= Helpers::editorLink($row['file'], $row['line']) ?>
<?php	else: ?>
			<i>inner-code</i><?php if (isset($row['line'])) echo ':', $row['line'] ?>
<?php	endif ?>

		</div>

		<div class="callstack-callee">
<?php if ($clickable): ?>
			<a data-tracy-ref="^div + div" class="tracy-toggle<?php if ($expanded !== $key) echo ' tracy-collapsed' ?>"><?php endif ?>
<?php if (isset($row['class'])) echo Helpers::escapeHtml($row['class']), '::' ?><b><?= Helpers::escapeHtml($row['function']) ?></b> <?= empty($row['args']) ? '()' : '(...)' ?>
<?php if ($clickable): ?></a><?php endif ?>

		</div>

<?php	if ($clickable): ?>
		<div class="callstack-additional<?php if ($expanded !== $key) echo ' tracy-collapsed' ?>">
<?php		if (isset($row['file']) && is_file($row['file'])): ?>
			<?= BlueScreen::highlightFile($row['file'], $row['line']) ?>
<?php		endif ?>


<?php		if (!empty($row['args'])): ?>
			<table class="args">
<?php
			try {
				$r = isset($row['class']) ? new \ReflectionMethod($row['class'], $row['function']) : new \ReflectionFunction($row['function']);
				$params = $r->getParameters();
			} catch (\Exception $e) {
				$params = [];
			}
			foreach ($row['args'] as $k => $v) {
				$argName = isset($params[$k]) && !$params[$k]->isVariadic() ? $params[$k]->name : $k;
				echo '<tr><th>', Helpers::escapeHtml((is_string($argName) ? '$' : '#') . $argName), '</th><td>';
				echo $dump($v, (string) $argName);
				echo "</td></tr>\n";
			}
?>
			</table>
<?php		endif ?>
		</div>
<?php	endif ?>
<?php endforeach ?>
	</div>
	</div>
</section>
