<?php

/**
 * Debugger bluescreen template.
 *
 * This file is part of the Tracy (https://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

declare(strict_types=1);

namespace Tracy;

/**
 * @var \Throwable $ex
 * @var array[] $actions
 * @var string $title
 * @var BlueScreen $this
 */

$title = $ex instanceof \ErrorException
	? Helpers::errorTypeToString($ex->getSeverity())
	: Helpers::getClass($ex);
$code = $ex->getCode() ? ' #' . $ex->getCode() : '';

?>
<section id="tracy-bs-error" class="section">
	<?php if ($ex->getMessage()): ?><p><?= Helpers::escapeHtml($title . $code) ?></p><?php endif ?>


	<h1><span><?= $this->formatMessage($ex) ?: Helpers::escapeHtml($title . $code) ?></span>
<?php foreach ($actions as $item): ?>
	<a href="<?= Helpers::escapeHtml($item['link']) ?>" class="action"<?= empty($item['external']) ? '' : ' target="_blank" rel="noreferrer noopener"'?>><?= Helpers::escapeHtml($item['label']) ?>&#x25ba;</a>
<?php endforeach ?>
	</h1>
</section>

<?php if ($ex->getPrevious()): ?>
<div class="caused">
	<a href="#tracyCaused">Caused by <?= Helpers::escapeHtml(Helpers::getClass($ex->getPrevious())) ?></a>
</div>
<?php endif ?>
