<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var \Throwable $ex
 * @var int $expanded
 */

?>
<div class="panel">
	<h2><a data-tracy-ref="^+" class="tracy-toggle<?= ($collapsed = $expanded !== null) ? ' tracy-collapsed' : '' ?>">Source file</a></h2>

	<div class="<?= $collapsed ? 'tracy-collapsed ' : '' ?>inner">
		<p><b>File:</b> <?= Helpers::editorLink($ex->getFile(), $ex->getLine()) ?></p>
		<?php if (is_file($ex->getFile())): ?><?= BlueScreen::highlightFile($ex->getFile(), $ex->getLine()) ?><?php endif ?>

	</div>
</div>
