<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var string $source
 * @var string[] $httpHeaders
 * @var callable $dump
 * @var bool $headersSent
 * @var ?string $headersFile
 * @var ?int $headersLine
 */

if (Helpers::isCli()) {
	return;
}
?>
<section class="section">
	<h2 class="section-label"><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">HTTP request</a></h2>

	<div class="section-panel tracy-collapsed">
		<h3><?= Helpers::escapeHtml($_SERVER['REQUEST_METHOD'] ?? 'URL') ?></h3>
		<p><a href="<?= Helpers::escapeHtml($source) ?>" target="_blank" rel="noreferrer noopener"><?= Helpers::escapeHtml($source) ?></a></p>

		<h3>Headers</h3>
		<div class="pane">
			<table class="tracy-sortable">
<?php foreach ($httpHeaders as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php endforeach ?>
			</table>
		</div>


<?php foreach (['_GET', '_POST', '_COOKIE'] as $name): ?>
		<h3>$<?= Helpers::escapeHtml($name) ?></h3>
<?php	if (empty($GLOBALS[$name])):?>
		<p><i>empty</i></p>
<?php	else: ?>
		<div class="pane">
			<table class="tracy-sortable">
<?php	foreach ($GLOBALS[$name] as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php	endforeach ?>
			</table>
		</div>
<?php	endif ?>
<?php endforeach ?>
	</div>
</section>

<section class="section">
	<h2 class="section-label"><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">HTTP response</a></h2>

	<div class="section-panel tracy-collapsed">
		<h3>Headers</h3>
<?php if (headers_list()): ?>
		<div class="pane">
			<table class="tracy-sortable">
<?php	foreach (headers_list() as $s): $s = explode(':', $s, 2); ?>
				<tr><th><?= Helpers::escapeHtml($s[0]) ?></th><td><?= $dump(trim($s[1]), $s[0]) ?></td></tr>
<?php	endforeach ?>
			</table>
		</div>
<?php else: ?>
		<p><i>no headers</i></p>
<?php endif ?>


<?php if ($headersSent && $headersFile && @is_file($headersFile)): ?>
		<p>Headers have been sent, output started at <?= Helpers::editorLink($headersFile, $headersLine) ?> <a data-tracy-ref="^p + div" class="tracy-toggle tracy-collapsed">source</a></p>
		<div class="tracy-collapsed"><?= BlueScreen::highlightFile($headersFile, $headersLine) ?></div>
<?php elseif ($headersSent): ?>
		<p>Headers have been sent</p>
<?php else: ?>
		<p>Headers were not sent at the time of the exception</p>
<?php endif ?>
	</div>
</section>
