<?php

declare(strict_types=1);

namespace Tracy;

/**
 * @var string $source
 * @var callable $dump
 */

if (!Helpers::isCli()) {
	return;
}
?>
<div class="panel">
	<h2><a data-tracy-ref="^+" class="tracy-toggle tracy-collapsed">CLI request</a></h2>

	<div class="tracy-collapsed inner">
		<h3>Process ID <?= Helpers::escapeHtml(getmypid()) ?></h3>
		<pre>php<?= Helpers::escapeHtml(explode('):', $source, 2)[1]) ?></pre>

		<h3>Arguments</h3>
		<div class="outer">
			<table>
<?php foreach ($_SERVER['argv'] as $k => $v): ?>
				<tr><th><?= Helpers::escapeHtml($k) ?></th><td><?= $dump($v, $k) ?></td></tr>
<?php endforeach ?>
			</table>
		</div>
	</div>
</div>
