<?php

/**
 * Debug Bar panels template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 *
 * @param  array $rows
 */

namespace Tracy;

use Tracy;


foreach ($rows as $row) {
	foreach ($row->panels as $panel) {
?>
	<div class="tracy-panel" id="tracy-debug-panel-<?= $panel->id ?>">
		<?php if ($panel->panel): echo $panel->panel ?>
		<div class="tracy-icons">
			<a href="#" title="open in window">&curren;</a>
			<a href="#" rel="close" title="close window">&times;</a>
		</div>
		<?php endif ?>
	</div><?php
	}
}
