<?php

/**
 * Debug Bar: tab "info" template.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 */

namespace Tracy;

use Tracy;

$this->time = microtime(TRUE) - Debugger::$time;

?>
<span title="Execution time">
<svg viewBox="0 0 2048 2048"><path fill="#3987d4" d="m1792 254.83v1538h-256v-1538z"/><path fill="#4f96dc" d="m1408 897.57v894.3h-256v-894.3z"/><path fill="#6ba9e6" d="m1024 643.87v1149h-256v-1149z"/><path fill="#86bbf0" d="m640 1153.6v639.3h-256v-639.3z"/>
</svg><?php echo number_format($this->time * 1000, 1, '.', ' ') ?> ms</span>
