<?php

/**
 * Debug Bar screen template.
 *
 * It uses Silk Icons created by Mark James and released under Creative Commons Attribution 2.5 License.
 *
 * This file is part of the Tracy (http://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (http://davidgrudl.com)
 *
 * @param  array $panels
 * @param  array $info
 * @return void
 */

namespace Tracy;

use Tracy;

?>




<!-- Tracy Debug Bar -->

<?php ob_start() ?>
&nbsp;

<style id="tracy-debug-style" class="tracy-debug">
<?php readfile(__DIR__ . '/bar.css') ?>
<?php readfile(__DIR__ . '/dumper.css') ?>
</style>

<script id="tracy-debug-script">
<?php readfile(__DIR__ . '/Tracy.js') ?>
<?php readfile(__DIR__ . '/Query.js') ?>
<?php readfile(__DIR__ . '/bar.js') ?>
<?php readfile(__DIR__ . '/dumper.js') ?>
</script>


<?php foreach ($panels as $panel): if (!$panel['panel']) continue; ?>
	<div class="tracy-panel" id="tracy-debug-panel-<?php echo $panel['id'] ?>">
		<?php echo $panel['panel'] ?>
		<div class="tracy-icons">
			<a href="#" title="open in window">&curren;</a>
			<a href="#" rel="close" title="close window">&times;</a>
		</div>
	</div>
<?php endforeach ?>

<div id="tracy-debug-bar">
	<ul>
		<li id="tracy-debug-logo" title="<?php echo htmlSpecialChars(implode(" |\n", $info))?>">&nbsp;<span>Tracy</span></li>
		<?php foreach ($panels as $panel): if (!$panel['tab']) continue; ?>
		<?php if (!empty($panel['previous'])) echo '</ul><ul class="tracy-previous">'; ?>
		<li><?php if ($panel['panel']): ?><a href="#" rel="<?php echo $panel['id'] ?>"><?php echo trim($panel['tab']) ?></a><?php else: echo '<span>', trim($panel['tab']), '</span>'; endif ?></li>
		<?php endforeach ?>
		<li><a href="#" rel="close" title="close debug bar">&times;</a></li>
	</ul>
</div>
<?php $output = ob_get_clean(); ?>


<script>
(function() {
	var debug = document.body.appendChild(document.createElement('div'));
	if (!document.addEventListener) {
		debug.innerHTML = '<div style="position:fixed;right:0;bottom:0;z-index:30000;font:normal normal 12px/21px sans-serif;color:#333;background:#EDEAE0;border:1px solid #ccc;padding:.2em">Warning: Tracy requires IE 9+<\/div>';
		return;
	}

	window.addEventListener('load', function() {
		debug.id = 'tracy-debug';
		debug.innerHTML = <?php echo json_encode(Helpers::fixEncoding($output)) ?>;
		for (var i = 0, scripts = debug.getElementsByTagName('script'); i < scripts.length; i++) eval(scripts[i].innerHTML);
		Tracy.Dumper.init(<?php echo json_encode(Dumper::fetchLiveData()) ?>);
		Tracy.Debug.init();
		debug.style.display = 'block';
	});
})();
</script>

<!-- /Tracy Debug Bar -->
