<?php

/**
 * Nette Framework - Debug Bar: panel "error" template.
 *
 * @category   Nette
 * @package    Nette
 */

/*namespace Nette;*/
?>
<h1>Errors</h1>

<?php $relative = isset($_SERVER['SCRIPT_FILENAME']) ? strtr(dirname(dirname($_SERVER['SCRIPT_FILENAME'])), '/', DIRECTORY_SEPARATOR) : NULL ?>

<div class="nette-inner">
<table>
<?php foreach (self::$errors as $i => $item): ?>
<tr class="<?php echo $i++ % 2 ? 'nette-alt' : '' ?>">
	<td><pre><?php echo $relative ? str_replace($relative, "...", $item) : $item ?></pre></td>
</tr>
<?php endforeach ?>
</table>
</div>