<?php

/**
 * Nette Framework - Profiler screen template.
 *
 * Copyright (c) 2004, 2008 David Grudl (http://davidgrudl.com)
 *
 * This source file is subject to the "Nette license" that is bundled
 * with this package in the file license.txt.
 *
 * For more information please see http://nettephp.com
 *
 * @author     David Grudl
 * @copyright  Copyright (c) 2004, 2008 David Grudl
 * @license    http://nettephp.com/license  Nette license
 * @link       http://nettephp.com
 * @category   Nette
 * @package    Nette
 * @version    $Revision$ $Date$
 *
 * @param  array     $colophons
 */

?>
</pre></xmp>

<style type="text/css">
/* <![CDATA[ */
	#netteProfilerContainer {
		position: absolute;
		right: 5px;
		bottom: 5px;
	}

	#netteProfiler {
		position: relative;
		margin: 0;
		padding: 1px;
		width: 350px;
		color: black;
		background: #EEE;
		border: 1px dotted gray;
		cursor: move;
		opacity: .70;
		=filter: alpha(opacity=70);
	}

	#netteProfiler:hover {
		opacity: 1;
		=filter: none;
	}

	#netteProfiler li {
		margin: 0;
		padding: 1px;
		font: normal normal 11px/1.4 Consolas, Arial;
		text-align: left;
		list-style: none;
	}

	#netteProfiler span[title] {
		border-bottom: 1px dotted gray;
		cursor: help;
	}
/* ]]> */
</style>


<div id="netteProfilerContainer">
<ul id="netteProfiler">
	<?php foreach ($colophons as $callback): ?>
	<?php foreach ((array) call_user_func($callback, 'profiler') as $line): ?><li><?php echo $line, "\n" ?></li><?php endforeach ?>
	<?php endforeach ?>
	<li>
	<?php
		$list = get_included_files();
		$same = explode(DIRECTORY_SEPARATOR, $list[0]);
		foreach ($list as $file) {
			foreach (explode(DIRECTORY_SEPARATOR, $file) as $key => $value) {
				if (isset($same[$key]) && $same[$key] === $value) continue;
				array_splice($same, $key);
				break;
			}
		}
		$same = strlen(implode(DIRECTORY_SEPARATOR, $same)) + 1;
		foreach ($list as $key => $file) {
			$list[$key] = substr($file, $same);
		}
		$al = class_exists(/*Nette::Loaders::*/'AutoLoader', FALSE) ?  /*Nette::Loaders::*/AutoLoader::$count : 0;
	?>
	<span title="<?php echo implode(" \n", $list) ?>"><?php echo count($list), '/', $al ?> files</span>,

	<?php
		$extClasses = array('stdClass', 'Exception', 'ErrorException', 'Traversable', 'IteratorAggregate', 'Iterator', 'ArrayAccess', 'Serializable');
		foreach (get_loaded_extensions() as $ext) {
			$ref = new ReflectionExtension($ext);
			$extClasses = array_merge($extClasses, $ref->getClassNames());
		}
	?>
	<?php $list = array_diff(get_declared_classes(), $extClasses); ?>
	<span <?php if ($list) echo 'title="', implode(", ", $list), '"' ?>><?php echo count($list) ?> classes</span>,

	<?php $list = array_diff(get_declared_interfaces(), $extClasses); ?>
	<span <?php if ($list) echo 'title="',  implode(", ", $list), '"' ?>><?php echo count($list) ?> intf</span>,

	<?php $list = get_defined_functions(); $list = (array) @$list['user']; ?>
	<span <?php if ($list) echo 'title="', implode(", ", $list), '"' ?>><?php echo count($list) ?> func</span>,

	<?php $list = get_defined_constants(TRUE); $list = array_keys((array) @$list['user']); ?>
	<span <?php if ($list) echo 'title="', implode(", ", $list), '"' ?>><?php echo count($list) ?> consts</span>
	</li>
</ul>
</div>


<script type="text/javascript">
/* <![CDATA[ */
document.getElementById('netteProfiler').onmousedown = function(e) {
	e = e || event;
	this.posX = parseInt(this.style.left + '0');
	this.posY = parseInt(this.style.top + '0');
	this.mouseX = e.clientX;
	this.mouseY = e.clientY;

	var thisObj = this;

	document.documentElement.onmousemove = function(e) {
		e = e || event;
		thisObj.style.left = (e.clientX - thisObj.mouseX + thisObj.posX) + "px";
		thisObj.style.top = (e.clientY - thisObj.mouseY + thisObj.posY) + "px";
	};

	document.documentElement.onmouseup = function(e) {
		document.documentElement.onmousemove = null;
		document.documentElement.onmouseup = null;
	};
};
/* ]]> */
</script>
