<?php

/**
 * Nette Framework - Profiler screen template.
 *
 * Copyright (c) 2004, 2008 David Grudl (http://davidgrudl.com)
 *
 * This source file is subject to the "Nette license" that is bundled
 * with this package in the file license.txt.
 *
 * For more information please see http://nettephp.com/
 *
 * @author     David Grudl
 * @copyright  Copyright (c) 2004, 2008 David Grudl
 * @license    http://nettephp.com/license  Nette license
 * @link       http://nettephp.com/
 * @category   Nette
 * @package    Nette
 * @version    $Revision$ $Date$
 *
 * @param  array     $colophons
 */

?>
<style type="text/css">
/* <![CDATA[ */
	#netteProfilerContainer {
		position: absolute;
		right: 5px;
		bottom: 5px
	}

	#netteProfiler {
		position: relative;
		color: white;
		background: black;
		font-size: 10px;
		text-align: left;
		font-family: Arial;
		width: 250px;
		cursor: move
	}
/* ]]> */
</style>


<div id="netteProfilerContainer">
<table id="netteProfiler">
<tr>
	<td>
	<?php $list = get_included_files(); ?>
	<?php $al = class_exists(/*Nette::Loaders::*/'AutoLoader', FALSE) ?  /*Nette::Loaders::*/AutoLoader::$count : 0; ?>
	<span title="<?php echo implode("\n", $list) ?>"><?php echo count($list), '/', $al ?> files</span>,

	<?php $list = array_diff(get_declared_classes(), spl_classes()); ?>
	<span title="<?php echo implode(", ", $list) ?>"><?php echo count($list) ?> classes</span>,

	<?php $list = get_declared_interfaces(); ?>
	<span title="<?php echo implode(", ", $list) ?>"><?php echo count($list) ?> interfaces</span>,

	<?php $list = get_defined_functions(); $list = (array) @$list['user']; ?>
	<span title="<?php echo implode(", ", $list) ?>"><?php echo count($list) ?> functions</span>,

	<?php $list = get_defined_constants(TRUE); $list = array_keys((array) @$list['user']); ?>
	<span title="<?php echo implode(", ", $list) ?>"><?php echo count($list) ?> consts</span>
	</td>
</tr>

<?php foreach ($colophons as $callback): ?>
<?php foreach ((array) call_user_func($callback, 'profiler') as $line): ?><tr><td><?php echo htmlSpecialChars($line), "\n" ?></td></tr><?php endforeach ?>
<?php endforeach ?>
</table>
</div>


<script type="text/javascript">
/* <![CDATA[ */
document.getElementById('netteProfiler').onmousedown = function(e) {
	e = e || event;
	/*this.style.position = "relative";*/
	this.posX = parseInt(this.style.left + '0');
	this.posY = parseInt(this.style.top + '0');
	this.mouseX = e.clientX;
	this.mouseY = e.clientY;

	var thisObj = this;

	document.documentElement.onmousemove = function(e) {
		e = e || event;
		thisObj.style.left = (e.clientX - thisObj.mouseX + thisObj.posX) + "px";
		thisObj.style.top = (e.clientY - thisObj.mouseY + thisObj.posY) + "px";
	};

	document.documentElement.onmouseup = function(e) {
		document.documentElement.onmousemove = null;
		document.documentElement.onmouseup = null;
	};
};
/* ]]> */
</script>
