<?php

/**
 * Debug Bar: panel "info" template.
 *
 * This file is part of the Tracy (https://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 */

declare(strict_types=1);

namespace Tracy;

/**
 * @var array $info
 * @var array $packages
 * @var array $devPackages
 */
?>
<style class="tracy-debug">
	#tracy-debug .tracy-InfoPanel td {
		white-space: nowrap;
	}
	#tracy-debug .tracy-InfoPanel td:nth-child(2) {
		font-weight: bold;
		width: 30%;
	}
	#tracy-debug .tracy-InfoPanel td[colspan='2'] b {
		float: right;
		margin-left: 2em;
	}
</style>

<h1>System info</h1>

<div class="tracy-inner tracy-InfoPanel">
<div class="tracy-inner-container">
<table class="tracy-sortable">
<?php foreach ($info as $key => $val): ?>
<tr>
<?php if (strlen($val) > 25): ?>
	<td colspan=2><?= Helpers::escapeHtml($key) ?> <b><?= Helpers::escapeHtml($val) ?></b></td>
<?php else: ?>
	<td><?= Helpers::escapeHtml($key) ?></td><td><?= Helpers::escapeHtml($val) ?></td>
<?php endif ?>
</tr>
<?php endforeach ?>
</table>

<?php if ($packages || $devPackages): ?>
	<h2><a class="tracy-toggle tracy-collapsed" data-tracy-ref="^div .tracy-InfoPanel-packages">Composer Packages (<?= count($packages), $devPackages ? ' + ' . count($devPackages) . ' dev' : '' ?>)</a></h2>

	<div class="tracy-InfoPanel-packages tracy-collapsed">
	<?php if ($packages): ?>
	<table class="tracy-sortable">
	<?php foreach ($packages as $package): ?>
		<tr><td><?= Helpers::escapeHtml($package->name) ?></td><td><?= Helpers::escapeHtml($package->version . (strpos($package->version, 'dev') !== false && $package->hash ? ' #' . substr($package->hash, 0, 4) : '')) ?></td></tr>
	<?php endforeach ?>
	</table>
	<?php endif ?>

	<?php if ($devPackages): ?>
	<h2>Dev Packages</h2>
	<table class="tracy-sortable">
	<?php foreach ($devPackages as $package): ?>
		<tr><td><?= Helpers::escapeHtml($package->name) ?></td><td><?= Helpers::escapeHtml($package->version . (strpos($package->version, 'dev') !== false && $package->hash ? ' #' . substr($package->hash, 0, 4) : '')) ?></td></tr>
	<?php endforeach ?>
	</table>
	<?php endif ?>
	</div>
<?php endif ?>
</div>
</div>
