<?php

/**
 * Test: Tracy\BlueScreen::renderAsText()
 */

declare(strict_types=1);

use Tester\Assert;

require __DIR__ . '/../bootstrap.php';


function createException(string $message, int $code = 0, ?Throwable $prev = null): Throwable
{
	return new Exception($message, $code, $prev);
}


$blueScreen = new Tracy\BlueScreen;

$capture = function (Throwable $exception) use ($blueScreen) {
	ob_start();
	$blueScreen->renderAsText($exception);
	return ob_get_clean();
};


test('basic exception output is markdown', function () use ($capture) {
	$output = $capture(new RuntimeException('Test error'));
	Assert::match(
		'This is an error page generated by Tracy%A%# RuntimeException: Test error%A%in ' . __FILE__ . ':%d%%A%```php%A%```%A%',
		$output,
	);
});


test('error code in heading', function () use ($capture) {
	$output = $capture(createException('Oops', 42));
	Assert::match('%A%# Exception: Oops #42%A%', $output);
});


test('no error code when zero', function () use ($capture) {
	$output = $capture(createException('Oops'));
	Assert::match("%A%# Exception: Oops\n\nin %A%", $output);
});


test('stack trace section with arguments', function () use ($capture) {
	$fn = function (string $name, int $count) {
		throw new RuntimeException('Deep error');
	};
	try {
		$fn('hello', 42);
	} catch (RuntimeException $e) {
		$output = $capture($e);
	}

	Assert::match("%A%## Stack Trace%A%#0 = 'hello'%A%#1 = 42%A%", $output);
});


test('caused by section for chained exceptions', function () use ($capture) {
	$prev = new InvalidArgumentException('Root cause', 7);
	$exception = new RuntimeException('Wrapper', 5, $prev);
	$output = $capture($exception);

	Assert::match('%A%# RuntimeException: Wrapper #5%A%## Caused by: InvalidArgumentException: Root cause #7%A%', $output);
});


test('environment section', function () use ($capture) {
	$output = $capture(createException('env-test'));
	Assert::match('%A%## Environment%A%| PHP |%A%| Tracy |%a%', $output);
});


test('environment section hidden when disabled', function () {
	$bs = new Tracy\BlueScreen;
	$bs->showEnvironment = false;
	ob_start();
	$bs->renderAsText(createException('no-env-test'));
	$output = ob_get_clean();
	$foo = '##'; // so that it does not appear in the code
	Assert::notContains("$foo Environment", $output);
});


test('ErrorException uses severity name', function () use ($capture) {
	$output = $capture(new ErrorException('Bad value', 0, E_WARNING));
	Assert::match('%A%# Warning: Bad value%A%', $output);
});


test('source code shows error line marker', function () use ($capture) {
	$output = $capture(new Exception('marker test'));
	Assert::match('%A% > %a% | %A%', $output);
});


test('exception with custom properties', function () use ($capture) {
	$e = new class ('DB error') extends RuntimeException {
		public string $query = 'SELECT * FROM users';
	};
	$output = $capture($e);
	$foo = '##'; // so that it does not appear in the code
	Assert::match("%A%$foo Exception Properties%A%SELECT * FROM users%A%", $output);
});


test('no properties section for standard exception', function () use ($capture) {
	$output = $capture(createException('plain'));
	$foo = '##'; // so that it does not appear in the code
	Assert::notContains("$foo Exception Properties", $output);
});
