<?php

require_once '../../Nette/loader.php';

/*use Nette\Debug;*/

Debug::$time = 1201042800.1875;
Debug::$emailProbability = 1;
$_SERVER['HTTP_HOST'] = 'nettephp.com';
unset($_SERVER['REQUEST_TIME'], $_SERVER['HTTP_USER_AGENT'], $_SERVER['Path'], $_SERVER['PATH'], $_SERVER['PATHEXT'], $_SERVER['SERVER_SIGNATURE'], $_SERVER['SERVER_SOFTWARE']);

$errorLog = dirname(__FILE__) . '/log/php_error.log';
$email = 'debug';

foreach (glob(dirname($errorLog) . '/*') as $file) unlink($file); // delete all files

Debug::enable(E_ALL, $errorLog, $email);



function first($arg1, $arg2)
{
	second(TRUE, FALSE);
}



function second($arg1, $arg2)
{
	third(array(1, 2, 3));
}


function third($arg1)
{
	trigger_error('Error generated by trigger_error', E_USER_ERROR);
}


first(10, 'any string');